SELECT		COUNT([ID]) TOTAL_ENVIADO
        FROM [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[VW_EXTRATO_COMPILADO_AC] 
        WHERE [REFERENCIA] = '10/2023' AND SINDICALIZADO IN('S','B') AND DATA_ENVIO_AC IS NOT NULL  

/**

SELECT	COUNT([ID]) TOTAL_ENVIADO_ERRADO FROM [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[VW_EXTRATO_COMPILADO_AC] 
WHERE  DATA_ENVIO_AC > '2023-11-09 00:00:00.000' and [REFERENCIA] <> '10/2023'

**/
'