-- Atualizar os dados com o REPLICATE onde insere os zeros a  esquerda.
UPDATE [INTRANET_ANAJUSTRA].EXTRATO_MENSAL.PLANO_SAUDE SET [CPF] = REPLICATE('0', 11 - LEN([CPF])) + RTrim([CPF])  WHERE REFERENCIA IS NULL

UPDATE [INTRANET_ANAJUSTRA].EXTRATO_MENSAL.CONSIGNADO_NOVO SET [CPF] = REPLICATE('0', 11 - LEN([CPF])) + RTrim([CPF])  WHERE REFERENCIA IS NULL

UPDATE [INTRANET_ANAJUSTRA].EXTRATO_MENSAL.[VALORES_RRA] SET [CPF] = REPLICATE('0', 11 - LEN([CPF])) + RTrim([CPF]) WHERE [DATA DO PAGAMENTO] LIKE '%/10/2023%'





--update para inserir as mascaras
UPDATE [INTRANET_ANAJUSTRA].EXTRATO_MENSAL.PLANO_SAUDE  SET [CPF] = substring([CPF] ,1,3) + '.' + substring([CPF] ,4,3) + '.' + substring([CPF] ,7,3) + '-' + substring([CPF] ,10,2) WHERE REFERENCIA IS NULL

UPDATE [INTRANET_ANAJUSTRA].EXTRATO_MENSAL.CONSIGNADO_NOVO  SET [CPF] = substring([CPF] ,1,3) + '.' + substring([CPF] ,4,3) + '.' + substring([CPF] ,7,3) + '-' + substring([CPF] ,10,2) WHERE REFERENCIA IS NULL

UPDATE [INTRANET_ANAJUSTRA].EXTRATO_MENSAL.[VALORES_RRA]  SET [CPF] = substring([CPF] ,1,3) + '.' + substring([CPF] ,4,3) + '.' + substring([CPF] ,7,3) + '-' + substring([CPF] ,10,2) WHERE [DATA DO PAGAMENTO] LIKE '%/10/2023%'


--Update [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[CONSIGNADO_NOVO]
  --SET CPF = Replace(Replace(CPF,'-',''),'.','')

--  UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[APOLICES_CORRETORA]
--SET RAMO  = 'AUTO'
--  WHERE RAMO  = 'AUTOMOVEL'

  
--  UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[APOLICES_CORRETORA]
--SET RAMO  = 'RESIDENCIAL'
--  WHERE RAMO  = 'RESIDENCIA'


--    UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].PLANO_SAUDE
--SET OPERADORA  = 'UNIMED CEARÁ'
--  WHERE OPERADORA LIKE '%UNIMED CEAR%' AND REFERENCIA IS NULL




  UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[AGILIZA_PRECATORIOS]
SET REFERENCIA  = '10/2023'
  WHERE REFERENCIA IS NULL



  UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[INDIQUE_GANHE]
SET REFERENCIA  = '10/2023'
  WHERE REFERENCIA IS NULL

  
    UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].PLANO_SAUDE
SET REFERENCIA  = '10/2023'
  WHERE REFERENCIA IS NULL

      UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[CONSIGNADO_NOVO]
SET REFERENCIA  = '10/2023'
  WHERE REFERENCIA IS NULL


     UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[APOLICES_CORRETORA]
SET REFERENCIA  = '10/2023'
  WHERE REFERENCIA IS NULL

  
     UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[DECLARACOES_CONVENIOS]
SET REFERENCIA  = '10/2023'
  WHERE REFERENCIA IS NULL

  
     UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[DECLARACOES_CHEVROLET]
SET REFERENCIA  = '10/2023'
  WHERE REFERENCIA IS NULL

  

--      UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[APOLICES_CORRETORA]
--SET REFERENCIA  = '05/2023'
--  WHERE REFERENCIA IS NULL



--UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[CONSIGNADO_PORTABILIDADE]
--SET CPF  = REPLACE(CPF,' ','')
--WHERE REFERENCIA IS NULL AND CPF LIKE '% %'

UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].CONSIGNADO_PORTABILIDADE
SET REFERENCIA  = '10/2023'
WHERE REFERENCIA IS NULL

UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[VALORES_DIF_QUINTOS]
SET REFERENCIA  = '10/2023'
WHERE REFERENCIA IS NULL

UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[VALORES_PSS]
SET REFERENCIA  = '09/2023'
WHERE REFERENCIA IS NULL

UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[VALORES_RRA]
SET REFERENCIA  = '10/2023'
WHERE REFERENCIA IS NULL

UPDATE [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[VALORES_URV]
SET REFERENCIA  = '05/2023'
WHERE REFERENCIA IS NULL
