SELECT [ID_AC]
            ,[ID]
            ,[CPF]
            ,[ACOES_PARTICIPA]
            ,[ACOES_NAO_PATICIPA]
            ,[ACOES_INGRESSADAS]
            ,[ACOES_VALOR_RRA]
            ,[ACOES_DATA_RRA]
            ,[ACOES_BANCO_RRA]
            ,[ACOES_VALOR_PSS]
            ,[ACOES_DATA_PSS]
            ,[ACOES_BANCO_PSS]
            ,[ACOES_VALOR_QUINTOS]
            ,[ACOES_DATA_QUINTOS]
            ,[ACOES_BANCO_QUINTOS]
            ,[ACOES_VALOR_URV]
            ,[ACOES_DATA_URV]
            ,[ACOES_BANCO_URV]
            ,[ACOES_DECISOES_FAVORAVEIS]
            ,[CONV_QTDE_DECLARACOES]
            ,[CONV_LISTA_DESCONTO]
            ,[CONV_VEICULO_CHEVROLET]
            ,[CONV_DESCONTO_CHEVROLET]
            ,[CORR_QTDE_APOLICE_AUTO]
            ,[CORR_SEGURADORA_AUTO]
            ,[CORR_QTDE_APOLICE_RESID]
            ,[CORR_SEGURADORA_RESID]
            ,[CORR_QTDE_APOLICE_VIDA]
            ,[CORR_SEGURADORA_VIDA]
            ,[CORR_LIQUIDO_AUTO]
            ,[CORR_VAREJO_AUTO]
            ,[CORR_ECONOMIA_AUTO]
            ,[CORR_LIQUIDO_RESID]
            ,[CORR_VAREJO_RESID]
            ,[CORR_ECONOMIA_RESID]
            ,[CORR_LIQUIDO_VIDA]
            ,[CORR_VAREJO_VIDA]
            ,[CORR_ECONOMIA_VIDA]
            ,[CORR_NUM_DEPENDENTES]
            ,[CONS_QTDE_CONTRATOS_PORT]
            ,[CONS_ECON_MENSAL_PORT]
            ,[CONS_ECON_TOTAL_PORT]
            ,[CONS_QTDE_CONTRATOS_NOVO]
            ,[CONS_COD_CONTRATO_NOVO]
            ,[CONS_TAXA_NEGOCIADA_NOVO]
            ,[SAUDE_OPERADORA]
            ,[SAUDE_TIPO_PLANO]
            ,[SAUDE_QTDE_DEPENDENTES]
            ,[SAUDE_ECONOMIA_REAIS]
            ,[SAUDE_ECONOMIA_PORC]
            ,[AMIL_TIPO_PLANO]
            ,[AMIL_QTDE_DEPENDENTES]
            ,[AMIL_ECONOMIA_REAIS]
            ,[AMIL_ECONOMIA_PORC]
            ,[FINAN_QTDE_CHAMADOS]
            ,[PARLA_QTDE_CHAMADOS]
            ,[CALL_QTDE_LIGACOES]
            ,[CALL_QTDE_WHATSAPP]
            ,[INDIQUE_GANHE]
            ,[REFERENCIA]
            ,[DATA_GERACAO]
            ,[ENVIADO_SF]
            ,[DATA_ENVIO_AC]
            ,[DATA_RRA]
            ,[BANCO_RRA]
            ,[NOME_INDICADO]
            ,[CONTATO_IRPF]
            ,[DENTAL_UNI]
            ,[INDIQUE_GANHE_AC]
            ,[NOME_INDICADO_AC]
            ,[AGILIZA_PRECATORIOS] [CLIENTE_AGILIZA]
            , CASE WHEN CORRETORA_AUTO = 'SIM' OR CORRETORA_VIDA = 'SIM' OR CORRETORA_RESID = 'SIM' THEN 'SIM' ELSE 'NÃO' END CLIENTE_CORRETORA
            , CASE WHEN [CLIENTE_CONSIGNADO_PORT] = 'SIM' OR [CLIENTE_CONSIGNADO_NOVO] = 'SIM'  THEN 'SIM' ELSE 'NÃO' END CLIENTE_CONSIGNADO
            , CASE WHEN [CLIENTE_PLANO_SAUDE] = 'SIM' OR [CLIENTE_DENTAL_UNI] = 'SIM'  THEN 'SIM' ELSE 'NÃO' END CLIENTE_JUSAUDE
        FROM [INTRANET_ANAJUSTRA].[EXTRATO_MENSAL].[VW_EXTRATO_COMPILADO_AC] 
        WHERE [REFERENCIA] = '10/2023' AND SINDICALIZADO IN('S','B') AND DATA_ENVIO_AC IS not NULL